# Generated by Django 5.1.5 on 2025-01-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_remove_product_images_cartitem_cart_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_items',
            new_name='items',
        ),
    ]
