# Generated by Django 5.1.5 on 2025-01-30 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_remove_cart_items_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
